# Introducere
- Google Colabs
- GitHub
- Python


#Python
**Librării utile**
- Numpy
- Panda
- scikit-learn
- Matplotlib
- Keras



In [ ]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as plt
import scipy.io as sio
import keras


#Noțiuni de bază

**Operații simple**

In [ ]:
a = 5
b = 7
s1 = a+b
s2 = a-b
s3 = a/b
s4 = a*b
print('Rezultatul adunării este:'+ str(s1)) #funția str() - transformă numărul in stringș funcția print() afișează variabila
print('Rezultatul scăderii este:'+ str(s2))
print('Rezultatul impărțirii este:'+ str(s3))
print('Rezultatul înmulțirii este:'+ str(s4))
print(type(a))

Rezultatul adunării este:12
Rezultatul scăderii este:-2
Rezultatul impărțirii este:0.7142857142857143
Rezultatul înmulțirii este:35
<class 'int'>


**Vectori si matrici**

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = list(range(1,11)) #try changing range(1,11)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.random.randn(10)
print('10 numere aleatorii')
print(a)
a = 10+np.random.randn(10)
print(a)

10 numere aleatorii
[-0.44283647  0.00915476 -0.22830781  0.23039141  0.48685116  1.17669671
  0.6921239  -1.34712251  0.352549   -0.82764874]
[11.86151364  9.79067106 10.82745149 10.22777499 10.65766758 11.86440663
  9.33840749 10.24025601 10.18503915  9.17158366]


In [ ]:
a = [[0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 0]]
print(a)
print(type(a))

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
<class 'list'>


In [ ]:
a = np.zeros((4,4))
print(a)
print(type(a))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
a = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print('Primul rand din matrice')
print(a[0])
print('Primul element din matrice')
print(a[0][0])
print('Elementul i=2 (rand), j=1(coloana)')
print(a[2][1])
print(type(a))

Primul rand din matrice
[1, 4, 5, 12]
Primul element din matrice
1
Elementul i=2 (rand), j=1(coloana)
7
<class 'list'>


#Exercițiu 1a
Calculați și afișați valoarea:
[3546 + (7901-621)] * 2




In [ ]:
a = 3546
b = 7901
c = 621
s1 = b - c
s2 = a + s1
s3 = s2 * 2
#print('Rezultatul scaderii este:'+ str(s1))
#print('Rezultatul adunarii este:'+str(s2))
print('Rezultatul operatiei de mai sus este:'+str(s3))

Rezultatul operatiei de mai sus este:21652


#Exercițiu 1b
1.Creați și afișați o matrice de (3,3) elemente

2.Afișați elementul de pe linia trei coloana trei a matricei create

In [ ]:
# 1
a = np.array([[12, 27, 13],
     [5, 10, 99],
     [8, 78, 110]])
print(a)

# 2
print('Elementul i=2 (rand), j=2 (coloana), adica elementul de pe linia trei, coloana trei a matricei:', a[2][2])

print(type(a))

[[ 12  27  13]
 [  5  10  99]
 [  8  78 110]]
Elementul i=2 (rand), j=2 (coloana), adica elementul de pe linia trei, coloana trei a matricei: 110
<class 'numpy.ndarray'>


#Exercițiu 1c
1. Folosind librăria numpy, creați și afișați o matrice de (5,5) cu elemente aleatorii de la 1 la 100.
Utilizați funcția numpy - np.random.randint(nr max, size=(x,x))

2. Afișați elementul de la intersecția celor două diagonale ale matricei

3. Aranjați crescător elementele de pe a doua coloană a matricei și afișați rezultatul. *funcția numpy sort()*

4. Folosiți funcția *size()* și afișați rezultatul

5. Afișați lungimea matricei. *funcția len()*


In [ ]:
# 1
a = np.random.randint(100, size=(5,5))
print(a)

# 2
print('Elementul de la intersectia celor doua diagonale ale matricei:', a[2][2])

# 3

b = np.sort(a[:,1])
print('Elementele sortate crescator de pe a doua coloana a matricei a sunt:',  b)
#print(b)

# 4
c = np.size(a)
print('Dimensiunea matricei a este:', c)

# 5
d = len(a)
print('Lungimea matricei a este:', d)

[[ 4 67 24  7 35]
 [ 7 29 85 28 38]
 [72 22 47  9 67]
 [23 95 83 10 89]
 [34 48 73  1 67]]
Elementul de la intersectia celor doua diagonale ale matricei: 47
Elementele sortate crescator de pe a doua coloana a matricei a sunt: [22 29 48 67 95]
Dimensiunea matricei a este: 25
Lungimea matricei a este: 5


#Operații condiționale și repetitive

**Operatii conditionale**

Sintaxa

```
if <expression>:
  <statement>

```
```
if <expression>:
  <statement>
else:
  <statement>
```

```
if <expression>:
  <statement>
elif <expression>:
  <statement>
else <expression>:
  statement>
```
Exemple





    
  




**Operatori logici**


*   x < y  
*   x > y
*   x <= y
*   x >- y
*   x == y
*   x != y
*   x or y
*   x and y



**Operatii repetitive**

Sintaxa

```
for <variabila> in <vector>:
  <statement>
```


```
while <expresie>:
  <statement>
```

Exemple





# Exercitiu 2a
Creati un element aleatoriu intre 1 si 10. Utilizați funcția numpy - np.random.randint(nr max, size=(x,x)). In functie de valoarea elementului, afisati:


*   *Numarul generat este mai mic decat 5*
*   *Numarul generat este intre 5 si 8*
*   *Numarul generat este mai mare decat 8*

Afisati numarul generat. 




In [ ]:
a = np.random.randint(10)
print(a)

if a < 5:
  print('Numarul generat este mai mic decat 5')
elif a >= 5 and a <= 8:
  print('Numarul generat este intre 5 si 8')
else:
  print('Numarul generat este mai mare decat 8')



8
Numarul generat este intre 5 si 8


# Exercitiu 2b
Calculati factorial de 10 (10! = 1* 2 * 3 * 4 *....) folosing o functie repetitiva.





In [ ]:
num = 10
factorial = 1

for i in range(1, num):
  factorial = factorial * i
print('Factorial de', num, 'este', factorial)

Factorial de 10 este 362880
